# Generated by Django 2.0.6 on 2018-06-15 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='备注')),
                ('date_added', models.DateField(auto_now_add=True, verbose_name='入团时间')),
                ('name', models.CharField(max_length=50, verbose_name='参团人姓名')),
                ('signup', models.CharField(max_length=100, verbose_name='预报来源')),
                ('sex', models.CharField(choices=[('M', '男'), ('F', '女')], max_length=2, verbose_name='性别')),
                ('number', models.CharField(max_length=18, verbose_name='身份证号')),
                ('phone', models.CharField(max_length=11, verbose_name='联系电话')),
                ('bunk', models.CharField(choices=[('s', '上铺'), ('z', '中铺'), ('x', '下铺')], default='上铺', max_length=4, verbose_name='铺位')),
                ('money', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='结款')),
            ],
            options={
                'verbose_name_plural': '参团人员',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_name', models.CharField(max_length=100, verbose_name='旅行团名称')),
                ('text', models.TextField(verbose_name='旅行团简介')),
                ('route1', models.CharField(max_length=500, null=True, verbose_name='行程1')),
                ('route2', models.CharField(max_length=500, null=True, verbose_name='行程2')),
                ('route3', models.CharField(max_length=500, null=True, verbose_name='行程3')),
                ('route4', models.CharField(max_length=500, null=True, verbose_name='行程4')),
                ('route5', models.CharField(max_length=500, null=True, verbose_name='行程5')),
                ('date_added', models.DateField(auto_now_add=True, verbose_name='建立时间')),
                ('date_start', models.DateField(verbose_name='出发日期')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '旅行团名称',
                'verbose_name_plural': '旅行团名称',
            },
        ),
        migrations.AddField(
            model_name='entry',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_logs.Topic', verbose_name='旅行团名称'),
        ),
    ]
