# Generated by Django 2.0.6 on 2018-07-08 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': '旅行团', 'verbose_name_plural': '旅行团'},
        ),
        migrations.AlterField(
            model_name='entry',
            name='phone',
            field=models.CharField(max_length=12, verbose_name='联系电话'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='text',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='route1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='行程1'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='route2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='行程2'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='route3',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='行程3'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='route4',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='行程4'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='route5',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='行程5'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='text',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='旅行团备注'),
        ),
    ]
