# Generated by Django 2.0.6 on 2018-07-08 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0003_auto_20180708_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='text',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='旅行团备注'),
        ),
    ]
